// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qeycloak;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("qeycloak");
/**
 * Password for the Keycloak Account.
 * 
 */
    public String password() {
        return Codegen.stringProp("password").config(config).require();
    }
/**
 * Keycloak realm. Defaults to &#39;master&#39;.
 * 
 */
    public Optional<String> realm() {
        return Codegen.stringProp("realm").config(config).get();
    }
/**
 * URL of the Keycloak Server.
 * 
 */
    public String url() {
        return Codegen.stringProp("url").config(config).require();
    }
/**
 * Username for the Keycloak Account.
 * 
 */
    public String username() {
        return Codegen.stringProp("username").config(config).require();
    }
}
