// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qeycloak;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * Password for the Keycloak Account.
     * 
     */
    @Import(name="password", required=true)
    private Output<String> password;

    /**
     * @return Password for the Keycloak Account.
     * 
     */
    public Output<String> password() {
        return this.password;
    }

    /**
     * Keycloak realm. Defaults to &#39;master&#39;.
     * 
     */
    @Import(name="realm")
    private @Nullable Output<String> realm;

    /**
     * @return Keycloak realm. Defaults to &#39;master&#39;.
     * 
     */
    public Optional<Output<String>> realm() {
        return Optional.ofNullable(this.realm);
    }

    /**
     * URL of the Keycloak Server.
     * 
     */
    @Import(name="url", required=true)
    private Output<String> url;

    /**
     * @return URL of the Keycloak Server.
     * 
     */
    public Output<String> url() {
        return this.url;
    }

    /**
     * Username for the Keycloak Account.
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return Username for the Keycloak Account.
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.password = $.password;
        this.realm = $.realm;
        this.url = $.url;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param password Password for the Keycloak Account.
         * 
         * @return builder
         * 
         */
        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password Password for the Keycloak Account.
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param realm Keycloak realm. Defaults to &#39;master&#39;.
         * 
         * @return builder
         * 
         */
        public Builder realm(@Nullable Output<String> realm) {
            $.realm = realm;
            return this;
        }

        /**
         * @param realm Keycloak realm. Defaults to &#39;master&#39;.
         * 
         * @return builder
         * 
         */
        public Builder realm(String realm) {
            return realm(Output.of(realm));
        }

        /**
         * @param url URL of the Keycloak Server.
         * 
         * @return builder
         * 
         */
        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url URL of the Keycloak Server.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        /**
         * @param username Username for the Keycloak Account.
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username Username for the Keycloak Account.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public ProviderArgs build() {
            if ($.password == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "password");
            }
            if ($.url == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "url");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "username");
            }
            return $;
        }
    }

}
