// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qeycloak.realm;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RealmArgs extends com.pulumi.resources.ResourceArgs {

    public static final RealmArgs Empty = new RealmArgs();

    @Import(name="accountTheme")
    private @Nullable Output<String> accountTheme;

    public Optional<Output<String>> accountTheme() {
        return Optional.ofNullable(this.accountTheme);
    }

    @Import(name="adminTheme")
    private @Nullable Output<String> adminTheme;

    public Optional<Output<String>> adminTheme() {
        return Optional.ofNullable(this.adminTheme);
    }

    @Import(name="displayName")
    private @Nullable Output<String> displayName;

    public Optional<Output<String>> displayName() {
        return Optional.ofNullable(this.displayName);
    }

    @Import(name="displayNameHtml")
    private @Nullable Output<String> displayNameHtml;

    public Optional<Output<String>> displayNameHtml() {
        return Optional.ofNullable(this.displayNameHtml);
    }

    @Import(name="emailTheme")
    private @Nullable Output<String> emailTheme;

    public Optional<Output<String>> emailTheme() {
        return Optional.ofNullable(this.emailTheme);
    }

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="loginTheme")
    private @Nullable Output<String> loginTheme;

    public Optional<Output<String>> loginTheme() {
        return Optional.ofNullable(this.loginTheme);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    private RealmArgs() {}

    private RealmArgs(RealmArgs $) {
        this.accountTheme = $.accountTheme;
        this.adminTheme = $.adminTheme;
        this.displayName = $.displayName;
        this.displayNameHtml = $.displayNameHtml;
        this.emailTheme = $.emailTheme;
        this.enabled = $.enabled;
        this.loginTheme = $.loginTheme;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RealmArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RealmArgs $;

        public Builder() {
            $ = new RealmArgs();
        }

        public Builder(RealmArgs defaults) {
            $ = new RealmArgs(Objects.requireNonNull(defaults));
        }

        public Builder accountTheme(@Nullable Output<String> accountTheme) {
            $.accountTheme = accountTheme;
            return this;
        }

        public Builder accountTheme(String accountTheme) {
            return accountTheme(Output.of(accountTheme));
        }

        public Builder adminTheme(@Nullable Output<String> adminTheme) {
            $.adminTheme = adminTheme;
            return this;
        }

        public Builder adminTheme(String adminTheme) {
            return adminTheme(Output.of(adminTheme));
        }

        public Builder displayName(@Nullable Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        public Builder displayNameHtml(@Nullable Output<String> displayNameHtml) {
            $.displayNameHtml = displayNameHtml;
            return this;
        }

        public Builder displayNameHtml(String displayNameHtml) {
            return displayNameHtml(Output.of(displayNameHtml));
        }

        public Builder emailTheme(@Nullable Output<String> emailTheme) {
            $.emailTheme = emailTheme;
            return this;
        }

        public Builder emailTheme(String emailTheme) {
            return emailTheme(Output.of(emailTheme));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder loginTheme(@Nullable Output<String> loginTheme) {
            $.loginTheme = loginTheme;
            return this;
        }

        public Builder loginTheme(String loginTheme) {
            return loginTheme(Output.of(loginTheme));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public RealmArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("RealmArgs", "name");
            }
            return $;
        }
    }

}
