// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.qeycloak.realm;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.qeycloak.Utilities;
import com.pulumi.qeycloak.realm.RealmArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="qeycloak:realm:Realm")
public class Realm extends com.pulumi.resources.CustomResource {
    @Export(name="accountTheme", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> accountTheme;

    public Output<Optional<String>> accountTheme() {
        return Codegen.optional(this.accountTheme);
    }
    @Export(name="adminTheme", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> adminTheme;

    public Output<Optional<String>> adminTheme() {
        return Codegen.optional(this.adminTheme);
    }
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> displayName;

    public Output<Optional<String>> displayName() {
        return Codegen.optional(this.displayName);
    }
    @Export(name="displayNameHtml", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> displayNameHtml;

    public Output<Optional<String>> displayNameHtml() {
        return Codegen.optional(this.displayNameHtml);
    }
    @Export(name="emailTheme", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> emailTheme;

    public Output<Optional<String>> emailTheme() {
        return Codegen.optional(this.emailTheme);
    }
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enabled;

    public Output<Optional<Boolean>> enabled() {
        return Codegen.optional(this.enabled);
    }
    @Export(name="loginTheme", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> loginTheme;

    public Output<Optional<String>> loginTheme() {
        return Codegen.optional(this.loginTheme);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="realmId", refs={String.class}, tree="[0]")
    private Output<String> realmId;

    public Output<String> realmId() {
        return this.realmId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Realm(java.lang.String name) {
        this(name, RealmArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Realm(java.lang.String name, RealmArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Realm(java.lang.String name, RealmArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("qeycloak:realm:Realm", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Realm(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("qeycloak:realm:Realm", name, null, makeResourceOptions(options, id), false);
    }

    private static RealmArgs makeArgs(RealmArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RealmArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/raushan606")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Realm get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Realm(name, id, options);
    }
}
