// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("qeycloak");

/**
 * Base path for the Keycloak API. Defaults to '/'.
 */
export declare const basePath: string;
Object.defineProperty(exports, "basePath", {
    get() {
        return __config.get("basePath") ?? "/";
    },
    enumerable: true,
});

/**
 * Allow insecure HTTPS client. Defaults to true.
 */
export declare const insecure: boolean;
Object.defineProperty(exports, "insecure", {
    get() {
        return __config.getObject<boolean>("insecure") ?? true;
    },
    enumerable: true,
});

/**
 * Password for the Keycloak Account.
 */
export declare const password: string;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password") ?? "";
    },
    enumerable: true,
});

/**
 * Keycloak realm. Defaults to 'master'.
 */
export declare const realm: string;
Object.defineProperty(exports, "realm", {
    get() {
        return __config.get("realm") ?? "master";
    },
    enumerable: true,
});

/**
 * URL of the Keycloak Server.
 */
export declare const url: string;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url") ?? "localhost:8080";
    },
    enumerable: true,
});

/**
 * Username for the Keycloak Account.
 */
export declare const username: string;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username") ?? "admin";
    },
    enumerable: true,
});

