// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { RealmArgs } from "./realm";
export type Realm = import("./realm").Realm;
export const Realm: typeof import("./realm").Realm = null as any;
utilities.lazyLoad(exports, ["Realm"], () => require("./realm"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "qeycloak:realm:Realm":
                return new Realm(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("qeycloak", "realm", _module)
