// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Realm extends pulumi.CustomResource {
    /**
     * Get an existing Realm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Realm {
        return new Realm(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'qeycloak:realm:Realm';

    /**
     * Returns true if the given object is an instance of Realm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Realm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Realm.__pulumiType;
    }

    declare public readonly accountTheme: pulumi.Output<string | undefined>;
    declare public readonly adminTheme: pulumi.Output<string | undefined>;
    declare public readonly displayName: pulumi.Output<string | undefined>;
    declare public readonly displayNameHtml: pulumi.Output<string | undefined>;
    declare public readonly emailTheme: pulumi.Output<string | undefined>;
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly loginTheme: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly realmId: pulumi.Output<string>;

    /**
     * Create a Realm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RealmArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["accountTheme"] = args?.accountTheme;
            resourceInputs["adminTheme"] = args?.adminTheme;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["displayNameHtml"] = args?.displayNameHtml;
            resourceInputs["emailTheme"] = args?.emailTheme;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["loginTheme"] = args?.loginTheme;
            resourceInputs["name"] = args?.name;
            resourceInputs["realmId"] = undefined /*out*/;
        } else {
            resourceInputs["accountTheme"] = undefined /*out*/;
            resourceInputs["adminTheme"] = undefined /*out*/;
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["displayNameHtml"] = undefined /*out*/;
            resourceInputs["emailTheme"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["loginTheme"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["realmId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Realm.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Realm resource.
 */
export interface RealmArgs {
    accountTheme?: pulumi.Input<string>;
    adminTheme?: pulumi.Input<string>;
    displayName?: pulumi.Input<string>;
    displayNameHtml?: pulumi.Input<string>;
    emailTheme?: pulumi.Input<string>;
    enabled?: pulumi.Input<boolean>;
    loginTheme?: pulumi.Input<string>;
    name: pulumi.Input<string>;
}
